### ISSUE TITLE
Warning encountered while using this action that causes the build to fail

### ISSUE THREAD

**Issue by basantPayU** [marcuslindblom/security-headers#6]
description:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
/entrypoint.sh: line 38: [: -ge: unary operator expected

```

yml file contents

```
name: security_header
on: 
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - env/sbox
      - env/qa
      - env/production
jobs:
  test_response_headers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: marcuslindblom/security-headers
      - name: response-header-security-check
        id: security-check
        uses: marcuslindblom/security-headers@v1.2.0
        with:
          url: someurl.com
          # url: ${{ secrets.SECURITY_HEADERS_URL }}
          followRedirects: true # This is optional
          grade: A
```
